name: Deploy djrise Frontend to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch entire history to avoid issues with Heroku

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          npm install -g heroku

      - name: Build
        run: npm run build

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "djrise"
          heroku_email: "andriikukharv@gmail.com"
          justlogin: true

      - name: Clear Heroku build cache
        run: heroku builds:cache:purge -a djrise --confirm djrise

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "djrise"
          heroku_email: "andriikukharv@gmail.com"
          healthcheck: "https://djrise-81215364f79c.herokuapp.com/"
          buildpack: heroku/nodejs
          dontuseforce: false
          usedocker: false
