name: Deploy djrise Frontend to Heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Heroku CLI
        run: |
          npm install -g heroku
          heroku --version

      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "djrise"
          heroku_email: "andriikukharv@gmail.com"
          healthcheck: "https://djrise-81215364f79c.herokuapp.com/"
